### ISSUE TITLE
Erle Drone

### ISSUE THREAD

**Issue by arronatron** [erlerobot/erle_gitbook#45]
Hi there,

I stumbled across you awesome gitbook as I looking into ordering a few ROD based drones for my research lab. 

I was wondering if you could let me know how I buy the erle drone?

Thank you
Arron

**Comment by imuguruza** [comment]
Hi Arron,

We don't sell that material nowadays...

Regards!

**Comment by arronatron** [comment]
Oh Really!! That is Unfortunate.

May I ask "Why you dont sell this drone anymore?"

Thank you
Arron

**Comment by LanderU** [comment]
We're now selling other kind of products, checkout the new web page: https://acutronicrobotics.com/
